In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = pd.read_csv("movies.csv")

In [3]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
data.shape

(4803, 24)

In [5]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director','original_language']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'original_language']


In [6]:
data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [7]:
data=data.fillna("")

In [8]:
# combining all the selected features

combined_features = data['genres']+' '+data['keywords']+' '+data['tagline']+' '+data['cast']+' '+data['director']+' '+data['original_language']

In [9]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [10]:
#CONVERTING TEXT DATA INTO VECTOR
vectorizer = TfidfVectorizer()

In [11]:
vectorizer.fit(combined_features)

TfidfVectorizer()

In [12]:
feature_vectors=vectorizer.transform(combined_features)

In [13]:
print(feature_vectors)

  (0, 17312)	0.20185863312549773
  (0, 17027)	0.2362922168681942
  (0, 17018)	0.12813614591803602
  (0, 16688)	0.19831426292450674
  (0, 16607)	0.12541945881301636
  (0, 15279)	0.07091600479711815
  (0, 14624)	0.15141634132650292
  (0, 14394)	0.33942491434120725
  (0, 14287)	0.21379417528322503
  (0, 14079)	0.20583803637232165
  (0, 13614)	0.10357957054889588
  (0, 13364)	0.15012303027709262
  (0, 13334)	0.2176171550320001
  (0, 13038)	0.19412033270357637
  (0, 11513)	0.27195076912003546
  (0, 11202)	0.09043921375601767
  (0, 10237)	0.16049105450885073
  (0, 8764)	0.22695468595009713
  (0, 7763)	0.11273627752842749
  (0, 5843)	0.16457685199337505
  (0, 5444)	0.10357957054889588
  (0, 5281)	0.11101935834163779
  (0, 4950)	0.24011519661696928
  (0, 4911)	0.03453638093174035
  (0, 3682)	0.21379417528322503
  :	:
  (4801, 7276)	0.3023734789665445
  (4801, 6942)	0.2884161588693086
  (4801, 4911)	0.03662740267957542
  (4801, 4839)	0.24697181882054411
  (4801, 3800)	0.3340565935833613
  (4801

# COSINE SIMILARITY

In [14]:
similarity = cosine_similarity(feature_vectors)

In [15]:
print(similarity)

[[1.         0.0731602  0.03890829 ... 0.0012222  0.00126498 0.0011916 ]
 [0.0731602  1.         0.03384574 ... 0.0367837  0.00110423 0.00104018]
 [0.03890829 0.03384574 1.         ... 0.00125046 0.05512248 0.00121915]
 ...
 [0.0012222  0.0367837  0.00125046 ... 1.         0.00129619 0.02770363]
 [0.00126498 0.00110423 0.05512248 ... 0.00129619 1.         0.00126374]
 [0.0011916  0.00104018 0.00121915 ... 0.02770363 0.00126374 1.        ]]


GETTING THE MOVIE NAME FROM THE USER


In [16]:
# creating a list with all the movie names given in the dataset
list_of_all_titles=list(data['original_title'].values)

In [17]:
movie=input("Enter your favorite movie : ")

Enter your favorite movie : iron man


In [18]:
#Getting similar movies
find_similar_movies=difflib.get_close_matches(movie,list_of_all_titles)
print(find_similar_movies)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [19]:
close_match=find_similar_movies[0]
close_match

'Iron Man'

In [20]:
# getting the index of the movie
index_of_movie=data[data.title == close_match]['index'].values[0]

In [21]:
print(index_of_movie)

68


In [22]:
#getting similar score
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, 0.034651711092169815), (1, 0.05556778067593926), (2, 0.014864549166554306), (3, 0.007709358491484986), (4, 0.033743060204178374), (5, 0.015049785150951484), (6, 0.07797319974531627), (7, 0.24030222148478422), (8, 0.009028543905665234), (9, 0.0770112494466352), (10, 0.07652233756895334), (11, 0.012908022428614139), (12, 0.014834102597908428), (13, 0.013394595300126936), (14, 0.09757508316635836), (15, 0.008346520594088642), (16, 0.2278715564403111), (17, 0.014191207564534139), (18, 0.042429788913276256), (19, 0.07972629431802007), (20, 0.08083662412805429), (21, 0.01219516759237631), (22, 0.007895988583183917), (23, 0.007560093008881947), (24, 0.013707194994274316), (25, 0.0011262310442939829), (26, 0.216574964784883), (27, 0.03156918897521504), (28, 0.06212500384638118), (29, 0.015199930789416876), (30, 0.08180953017829944), (31, 0.3154235385094266), (32, 0.0297872938558197), (33, 0.13187295553545794), (34, 0.0011345042914415915), (35, 0.03648620525506105), (36, 0.0328845732369135

In [23]:
len(similarity_score)

4803

In [24]:
#sorting movies based on their similar score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(68, 1.0), (79, 0.40954151270129446), (31, 0.3154235385094266), (7, 0.24030222148478422), (16, 0.2278715564403111), (26, 0.216574964784883), (85, 0.2071352744949083), (182, 0.19660400647660511), (511, 0.1679784684949355), (3623, 0.16197544802792216), (64, 0.15396184315117337), (203, 0.14904802860607627), (4401, 0.1484953518035033), (174, 0.14817618632850948), (101, 0.14504623634397906), (46, 0.14308508117134586), (169, 0.139045054873149), (1740, 0.13719470835214767), (94, 0.13710749351386797), (788, 0.13395646909900114), (126, 0.13353494814479042), (131, 0.1324222037628412), (33, 0.13187295553545794), (2487, 0.12408039157338295), (783, 0.1225813161713326), (138, 0.11940498015581812), (2442, 0.11827134555898897), (661, 0.11822812033513744), (607, 0.11484833188235834), (38, 0.11363384282434985), (2651, 0.11309583799734033), (353, 0.11249167668176277), (122, 0.10958039249972377), (1553, 0.10889149613736332), (1451, 0.10878387936017396), (242, 0.10736266164931861), (618, 0.103402312880773

In [25]:
#Printing the similar movies
print("So, you liked ",close_match,"\n Here are 30 best suggestions for you : \n")
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    suggested_movie=data[data.index==index]['title'].values[0]
    if (i<=30):
        print(i,'. ',suggested_movie)
        i=i+1

So, you liked  Iron Man 
 Here are 30 best suggestions for you : 

1 .  Iron Man
2 .  Iron Man 2
3 .  Iron Man 3
4 .  Avengers: Age of Ultron
5 .  The Avengers
6 .  Captain America: Civil War
7 .  Captain America: The Winter Soldier
8 .  Ant-Man
9 .  X-Men
10 .  Made
11 .  X-Men: Apocalypse
12 .  X2
13 .  The Helix... Loaded
14 .  The Incredible Hulk
15 .  X-Men: First Class
16 .  X-Men: Days of Future Past
17 .  Captain America: The First Avenger
18 .  Kick-Ass 2
19 .  Guardians of the Galaxy
20 .  Deadpool
21 .  Thor: The Dark World
22 .  G-Force
23 .  X-Men: The Last Stand
24 .  Duets
25 .  Mortdecai
26 .  The Last Airbender
27 .  Southland Tales
28 .  Zathura: A Space Adventure
29 .  Sky Captain and the World of Tomorrow
30 .  The Amazing Spider-Man 2


# Movie Recommendation System

In [26]:
mm=data['title'].tolist()
names=pd.DataFrame(mm,columns=['movie_name'])

In [27]:
names

movie_name
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

[4803 rows x 1 columns]

In [29]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles=list(data['original_title'].values)

find_similar_movies=difflib.get_close_matches(movie_name,list_of_all_titles)


close_match = find_similar_movies[0]

index_of_movie=data[data.title == close_match]['index'].values[0]

similarity_score=list(enumerate(similarity[index_of_movie]))

sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)

print("So, you liked ",close_match,"\n Here are 30 best suggestions for you : \n")
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    suggested_movie=data[data.index==index]['title'].values[0]
    if (i<=30):
        print(i,'. ',suggested_movie)
        i=i+1

 Enter your favourite movie name : super man
So, you liked  Superman 
 Here are 30 best suggestions for you : 

1 .  Superman
2 .  Superman II
3 .  Superman IV: The Quest for Peace
4 .  Man of Steel
5 .  Superman III
6 .  Crimson Tide
7 .  Superman Returns
8 .  Batman Returns
9 .  Suicide Squad
10 .  The Killer Inside Me
11 .  The Dark Knight Rises
12 .  Nanny McPhee and the Big Bang
13 .  Batman Begins
14 .  The Dark Knight
15 .  The Godfather
16 .  The Helix... Loaded
17 .  Batman
18 .  Batman
19 .  Batman & Robin
20 .  The Island of Dr. Moreau
21 .  The Hunting Party
22 .  The Abyss
23 .  Steel
24 .  Lethal Weapon 4
25 .  Dick Tracy
26 .  On the Waterfront
27 .  1941
28 .  Star Trek IV: The Voyage Home
29 .  Don Juan DeMarco
30 .  The Peacemaker
